### ISSUE TITLE
Querying values of an instance

### ISSUE THREAD

**Issue by gmarty** [flyingsparx/CENode#18]
Following on the example of the teacher from the documentation, I haven't been able to query specifically the age or any other values attached to the teacher instance.
Am I missing something here?

I tried:
"What is the age of Mrs Smith?"
"What is the value of age of Mrs Smith?"
"What is Mrs Smith's age?"

**Comment by willwebberley** [comment]
Hi @gmarty,

I'm sorry you've had problems with the library. As mentioned in the documentation, one of the key aims is to be a lightweight implementation of a much more robust system, and therefore some functionality is not available! We aim to provide a research-grade prototype to fulfil a decent level of CE-parsing and understanding, rudimentary NL-processing, and responses to simple questions.

In particular, in your case, the CENode library is not, in its current form, able to respond to NL/Ask inputs of the form you specified. Generally, users are able to query things like 
"what is Mrs Smith?"
"what is a teacher?"
And also things like 
"where is Mrs Smith?"
But that's about it for now.

The JavaScript interface is more complete, however, and should allow you to obtain the information you need:

```
node.instances.mrs_smith.age
```

will return the `age` property of an instance named `Mrs Smith`.

If you're using the library in an application, then I suggest you try to embed this kind of approach somehow into your workflow to support querying of specific properties. Otherwise, the library itself could be modified to allow the agent to answer more complex questions!
